name: "Auto Release on GitHub"

on:
  pull_request:
    branches:
      - main
    #types:
    #  - closed

env:
  GH_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-auto-release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3

      - name: Get Properties # https://github.com/marketplace/actions/action-read-json
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "package.json"

      - run: |
          gh release create v${{ steps.json_properties.outputs.version }} --generate-notes
